### ISSUE TITLE
Bundle docbookxi.rng for validation

### ISSUE THREAD

**Issue by edavis10** [napcs/docbook#10]
I'm getting a validation error every now and then. The error is a connection error and I think docbook.org might be limiting requests to their site.  I worked around it by downloading http://www.docbook.org/xml/5.0/rng/docbookxi.rng directly into the docbook directory and changing the `validator_cmd` (appears to be a bit faster using the filesystem too, no HTTP request needed now).

What do you think about bundling docbookxi.rng in the source directly? I can write a patch if you can tell me where that file should be stored in the source.

<pre>
 There are errors in your document
relmes verifier   Copyright(C) Sun Microsystems, Inc. 2001
parsing    http://www.docbook.org/xml/5.0/rng/docbookxi.rng
Connection refused
java.net.ConnectException: Connection refused
===================================
</pre>

**Comment by napcs** [comment]
Go for it. Put the file in the xsl folder in the root. I'm planning to
refactor the validation thing anway, and this would motivate me to do that
faster.
