### ISSUE TITLE
pdf.xsl - footer assumes only articles

### ISSUE THREAD

**Issue by edavis10** [napcs/docbook#11]
pdf.xsl's footer.content is hardcoded for articles so the Copyright year/holder don't appear for non-articles. Changing the xsl to `d:book` works for book types but I'm wondering if we could make this dynamic. Maybe run the xsl through erb when `generate` is used?

Bug source: https://github.com/napcs/docbook/blob/master/template/xsl/pdf.xsl#L271-273

**Comment by napcs** [comment]
Yes. In fact honestly the project generator really needs love. It's the only
piece that hasn't been fixed up. It was "good enough" code for the time
being, but there are many things that could be improved in there.

**Comment by napcs** [comment]
Update on this - it will happen in 1.5.1. Everything is in place to make this work.
