### ISSUE TITLE
Allow a quieter build

### ISSUE THREAD

**Issue by edavis10** [napcs/docbook#13]
Right now the build (rake) uses a lot of puts to print out status information. Standard UNIX programs are supposed to be quiet and print as little as possible and only print warnings and errors to the console. Some tools even provide a -q --quiet flag to silence all but the most fatal of errors.

I've added some code to reduce the output of the standard build. By default it is turned off to keep with the existing behavior of printing the build status but it can be enabled by passing an arg to rake.

<pre>
rake  # => standard output (default)
rake verbose=true # => standard output
rake verbose=yes # => standard output
rake verbose=no # => quiet output
rake verbose=f # => quiet output
rake verbose="please be quiet and stop printing all of this text to the console ;)" # => quiet output
</pre>

I didn't dig into the other build files for all of the messages (e.g. Validating your document...). In my opinion when verbose is turned off then only warnings and errors should be printed.

Pull request coming.

**Comment by napcs** [comment]
Not sure about this - I think the idea of making it less noisy by default is actually better, but there's also already code for debugging things. Need to think about the best way to handle this.

**Comment by edavis10** [comment]
Oh you're right, I missed the debug option.

What do you think about:
1. Add a class method to Docbook, called log that takes a string arg (message). Then it can handle both if rake or it's own methods should produce output (using puts)
2. Have make.rb call Docbook#log for all of it's output

I'm happy to have it be quiet by default, just didn't want to change the behavior too much without feedback.

**Comment by napcs** [comment]
default build in 1.5.0 is much quieter
