### ISSUE TITLE
using non-ascii characters

### ISSUE THREAD

**Issue by AlperKarapinar** [napcs/docbook#19]
Hi, i m not sure if this an issue, but i m having trouble using utf-8 charset for pdf output.

I m very new to docbook and apache fop.

Can you help where should i look for?

Thanks.

**Comment by AlperKarapinar** [comment]
Resolved this. 

Created an xconf file and setted fonts there. 
Required config file with -c parameter inside fob.rb fop_command.

**Comment by napcs** [comment]
Would you mind possibly sending a pull request for this? I think it would be super helpful to have a sample xconf file as part of the project and I'm not very clear how to do that.
