### ISSUE TITLE
localize dependencies

### ISSUE THREAD

**Issue by tj** [napcs/docbook#5]
Are they still at ~/docbook when installed? IMO it would be nice to
either localize all together or at least have that option

**Comment by napcs** [comment]
You can install with the rake task wherever you want, but the new xslt + rake can use a shell variable called SHORT_ATTENTION_SPAN_DOCBOOK_PATH and will use that instead. It now generates an intermediate fo.xml file that contains the paths, so if you use new machines or share code with others, the system can use the ENV variable and everything just works.

**Comment by tj** [comment]
cool sounds good!
