### ISSUE TITLE
use window or cygwin,rake pdf error:No such file or directory - book.tmp.pdf or book.pdf 

### ISSUE THREAD

**Issue by yangjiandong** [napcs/docbook#7]
install docbook to d:/home/docbook,and add to path,
generate book foobook with_sample
cd foobook
rake book.pdf
error:
(in D:/workspace/DocBook/example/foobook)
Short Attention Span Docbook v1.3.0.2
## (c) 2010 Brian P. Hogan

Using buildchain located at: d:/HOME/docbook
## Reminder: Nothing builds unless you've made changes to the Docbook file you're building.

Running preprocessing tasks
Validating your document...
Transforming XML...
java.lang.NoClassDefFoundError: com/icl/saxon/StyleSheet
Caused by: java.lang.ClassNotFoundException: com.icl.saxon.StyleSheet
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
Could not find the main class: com.icl.saxon.StyleSheet.  Program will exit.
Exception in thread "main" Finished XML transformation
FO processing halted - missing book.tmp.fo file.
Completed building book.pdf
Running postprocessing tasks
rake aborted!
No such file or directory - book.tmp.pdf or book.pdf

(See full trace by running task with --trace)

**Comment by napcs** [comment]
Ruby under Cygwin is not supported. If you're using that, I'm not sure how much I can tell you but I'll try to help.

The problem appears to be related to the part that builds the classpath. Can you post the lines of the Rakefile found in your book's folder?

**Comment by yangjiandong** [comment]
Rakefile:
#!/usr/bin/env ruby

# e.g. rake pdf                 # Create a PDF

# rake xhtml               # Create an XHTML file

# rake chm                 # Create a CHM help file

# rake pdf VALIDATE=false  # skips validation

#=================== Set path to DOCBOOK files =======

temp_root = ENV['SHORT_ATTENTION_SPAN_DOCBOOK_PATH'] || "d:/HOME/docbook"

# fix for windows paths with double-quotes and bad slashes.

DOCBOOK_ROOT = temp_root.gsub("\", "/").gsub('"', "")
require "#{DOCBOOK_ROOT}/make"

**Comment by napcs** [comment]
Cygwin is not supported. The path that's generated is wrong - it needs to be /d:/home rather that d:/home. But I have no plans to support a Cygwin environment.
