### ISSUE TITLE
Running rake install "aborts" rake no such file to load -- /home/edavis/.docbook/make

### ISSUE THREAD

**Issue by edavis10** [napcs/docbook#8]
I found an odd bug where rake is "aborted" but still runs.
1. Cleared out my ~/.docbook directory (where I had an older version installed to)
2. Upgraded (commit c666e84)
3. Ran `rake install DIR=/home/edavis/.docbook --trace`
4. Saw the error below
5. Ran `rake install DIR=/home/edavis/.docbook --trace` again
6. Error disappeared

I sounds like it might happen when first creating the docbook dir, maybe the code tries to load `make` too early. Running the install twice seems to fix it. I can reproduce it easily by clearing out ~/.docbook.

Output

<pre>

edavis@acheron:~/dev/docbook (master) [c666e84 small refactor of fop and base] 
$ rake install DIR=/home/edavis/.docbook --trace
** Invoke install (first_time)
** Invoke doc (first_time)
** Execute doc
rake aborted!
no such file to load -- /home/edavis/.docbook/make

(See full trace by running task with --trace)
** Execute install
 Copied make.rb to /home/edavis/.docbook/make.rb
 Copied version.rb to /home/edavis/.docbook/version.rb
 Copied README.txt to /home/edavis/.docbook/README.txt
 Copied hhc.exe to /home/edavis/.docbook/hhc.exe
 Copied jars to /home/edavis/.docbook/jars
 Copied lib to /home/edavis/.docbook/lib
 Copied xsl to /home/edavis/.docbook/xsl
 Copied readme_files to /home/edavis/.docbook/readme_files
 Copied Rakefile to /home/edavis/.docbook/Rakefile
 Copied generate to /home/edavis/.docbook/generate
 Copied generate.bat to /home/edavis/.docbook/generate.bat
 Copied template to /home/edavis/.docbook/template
Be sure to add
   export PATH=$PATH:/home/edavis/.docbook
 and optionally,
   export SHORT_ATTENTION_SPAN_DOCBOOK_PATH="/home/edavis/.docbook"
to your .bashrc or .bash_login or .bash_profile
</pre>

Second run

<pre>
edavis@acheron:~/dev/docbook (master) [c666e84 small refactor of fop and base] 
$ rake install DIR=/home/edavis/.docbook --trace
** Invoke install (first_time)
** Invoke doc (first_time)
** Execute doc
** Execute install
 Copied make.rb to /home/edavis/.docbook/make.rb
 Copied version.rb to /home/edavis/.docbook/version.rb
 Copied README.txt to /home/edavis/.docbook/README.txt
 Copied hhc.exe to /home/edavis/.docbook/hhc.exe
 Copied jars to /home/edavis/.docbook/jars
 Copied lib to /home/edavis/.docbook/lib
 Copied xsl to /home/edavis/.docbook/xsl
 Copied readme_files to /home/edavis/.docbook/readme_files
 Copied Rakefile to /home/edavis/.docbook/Rakefile
 Copied generate to /home/edavis/.docbook/generate
 Copied generate.bat to /home/edavis/.docbook/generate.bat
 Copied template to /home/edavis/.docbook/template
Be sure to add
   export PATH=$PATH:/home/edavis/.docbook
 and optionally,
   export SHORT_ATTENTION_SPAN_DOCBOOK_PATH="/home/edavis/.docbook"
to your .bashrc or .bash_login or .bash_profile
</pre>

**Comment by napcs** [comment]
Should be fixed. Rake runs another rake task externally to generate documentation. If you never installed, the env var wasn't set so now it gets passed.
